scoreboard objectives remove ateAppleDR 
scoreboard objectives remove ateMushStewDR 
scoreboard objectives remove atePChopDR 
scoreboard objectives remove ateCPChopDR 
scoreboard objectives remove ateBreadDR 
scoreboard objectives remove ateGappleDR 
scoreboard objectives remove ateFishDR 
scoreboard objectives remove ateCFishDR 
scoreboard objectives remove ateCakeDR 
scoreboard objectives remove ateCookieDR 
scoreboard objectives remove ateMelonDR 
scoreboard objectives remove ateBeefDR 
scoreboard objectives remove ateCBeefDR 
scoreboard objectives remove ateChickDR 
scoreboard objectives remove ateCChickDR 
scoreboard objectives remove ateRFleshDR 
scoreboard objectives remove ateSEyeDR 
scoreboard objectives remove ateCarrotDR 
scoreboard objectives remove atePotatoDR 
scoreboard objectives remove ateCPotatoDR 
scoreboard objectives remove atePPotatoDR 
scoreboard objectives remove atePPieDR 
scoreboard objectives remove ateRabbitDR 
scoreboard objectives remove ateCRabbitDR 
scoreboard objectives remove ateRStewDR 
scoreboard objectives remove ateMuttonDR 
scoreboard objectives remove ateCMuttonDR 
scoreboard objectives remove ateCFruitDR 
scoreboard objectives remove ateBeetrootDR 
scoreboard objectives remove ateBSoupDR 