scoreboard objectives add ateAppleDR stat.useItem.minecraft.apple
scoreboard objectives add ateMushStewDR stat.useItem.minecraft.mushroom_stew
scoreboard objectives add atePChopDR stat.useItem.minecraft.porkchop
scoreboard objectives add ateCPChopDR stat.useItem.minecraft.cooked_porkchop
scoreboard objectives add ateBreadDR stat.useItem.minecraft.bread
scoreboard objectives add ateGappleDR stat.useItem.minecraft.golden_apple
scoreboard objectives add ateFishDR stat.useItem.minecraft.fish
scoreboard objectives add ateCFishDR stat.useItem.minecraft.cooked_fish
scoreboard objectives add ateCakeDR stat.cakeSlicesEaten
scoreboard objectives add ateCookieDR stat.useItem.minecraft.cookie
scoreboard objectives add ateMelonDR stat.useItem.minecraft.melon
scoreboard objectives add ateBeefDR stat.useItem.minecraft.beef
scoreboard objectives add ateCBeefDR stat.useItem.minecraft.cooked_beef
scoreboard objectives add ateChickDR stat.useItem.minecraft.chicken
scoreboard objectives add ateCChickDR stat.useItem.minecraft.cooked_chicken
scoreboard objectives add ateRFleshDR stat.useItem.minecraft.rotten_flesh
scoreboard objectives add ateSEyeDR stat.useItem.minecraft.spider_eye
scoreboard objectives add ateCarrotDR stat.useItem.minecraft.carrot
scoreboard objectives add atePotatoDR stat.useItem.minecraft.potato
scoreboard objectives add ateCPotatoDR stat.useItem.minecraft.cooked_potato
scoreboard objectives add atePPotatoDR stat.useItem.minecraft.poisonous_potato
scoreboard objectives add atePPieDR stat.useItem.minecraft.pumpkin_pie
scoreboard objectives add ateRabbitDR stat.useItem.minecraft.rabbit
scoreboard objectives add ateCRabbitDR stat.useItem.minecraft.cooked_rabbit
scoreboard objectives add ateRStewDR stat.useItem.minecraft.rabbit_stew
scoreboard objectives add ateMuttonDR stat.useItem.minecraft.mutton
scoreboard objectives add ateCMuttonDR stat.useItem.minecraft.cooked_mutton
scoreboard objectives add ateCFruitDR stat.useItem.minecraft.chours_fruit
scoreboard objectives add ateBeetrootDR stat.useItem.minecraft.beetroot
scoreboard objectives add ateBSoupDR stat.useItem.minecraft.beetroot_soup